version: "3.5"

services:
  mysql:
    container_name: mysql80
    image: mysql:8
    ports:
      - "3369:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - backend
  php:
    restart: always
    container_name: prontrest_php
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hyperf:2.6.4 
    expose:
      - "9501"
    ports:
      - "9501:9501"
    volumes:
      - .:/var/www
    environment:
      TZ: Asia/Shanghai
    networks:
      - backend
    stdin_open: true
    tty: true
  redis: 
    container_name: redis50
    image: 'redis:5.0'
    ports:
      - 6399:6379
    networks:
      - backend
networks:
    backend:
      name: backend
